branch-defaults:
  main:
    environment: flask-continuous-delivery-env
    group_suffix: null
global:
  application_name: flask-continuous-delivery
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
